Models/Project.cs
using Guardian_BugTracker_23.Data.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Guardian_BugTracker_23.Models
{
    public class Project
    {
        private DateTimeOffset _created;
        private DateTimeOffset _startDate;
        private DateTimeOffset _endDate;
        public int Id { get; set; }
        [Required]
        [Display(Name = "Project Name")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and max {1} characters long.", MinimumLength = 2)]
        public string? Name { get; set; }
        public int CompanyId { get; set; }
        [Required]
        public string? Description { get; set; }
        
        [DataType(DataType.Date)]
        [Display(Name = "Date Created")]
        public DateTimeOffset Created {
            get => _created; 
            set
            {
                _created = value.ToUniversalTime();
            }
        }
        [DataType(DataType.Date)]
        [Display(Name = "Date Started")]
        public DateTimeOffset StartDate { 
            get => _startDate;
            set 
            {
                _startDate = value.ToUniversalTime();
            } 
        }
        [DataType(DataType.Date)]
        [Display(Name = "Date Ended")]
        public DateTimeOffset EndDate
        {
            get => _endDate;
            set 
            {
                _endDate = value.ToUniversalTime();            
            }
        
        }
        public BTProjectPriorities ProjectPriority { get; set; }

        //public int ProjectPriorityId { get; set; }

        // Image Properties
        [NotMapped]
        public IFormFile? ImageFormFile { get; set; }
        [Display(Name = "Project Image")]
        public byte[]? ImageFileData { get; set; }
        [Display(Name = "File Extension")]
        public string? ImageFileType { get; set; }

        public bool Archived { get; set; }

        // Navigation
        public virtual Company? Company { get; set; }
        //public virtual ProjectPriority? ProjectPriority { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; } = new HashSet<Ticket>();
        public virtual ICollection<BTUser> Members { get; set; } = new HashSet<BTUser>();
    }
}

Models/ViewModels/AssignPMViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Guardian_BugTracker_23.Models.ViewModels
{
    public class AssignPMViewModel
    {
        public int ProjectId { get; set; }
        public string? ProjectName { get; set; }
        public SelectList? PMList { get; set; }
        public string? PMId { get; set; }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Guardian_BugTracker_23.Data;
using Guardian_BugTracker_23.Models;
using Guardian_BugTracker_23.Services.Interfaces;
using Guardian_BugTracker_23.Data.Enums;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;
using Guardian_BugTracker_23.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using System.Runtime.InteropServices;
using Guardian_BugTracker_23.Services;

namespace Guardian_BugTracker_23.Controllers
{
    [Authorize]
    public class ProjectsController : BTBaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<ProjectsController> _logger;
        private readonly IBTProjectService _btProjectService;
        private readonly IBTRolesService _btRolesService;
        private readonly IBTFileService _btFileService;
        private readonly IImageService _imageService;
        private readonly UserManager<BTUser> _userManager;

        public ProjectsController(ApplicationDbContext context,
                                  ILogger<ProjectsController> logger,
                                  IBTProjectService bTProjectService,
                                  IBTRolesService bTRolesService,
                                  UserManager<BTUser> userManager,
                                  IBTFileService bTFileService,
                                  IImageService imageService
                                  )
        {
            _context = context;
            _logger = logger;
            _btProjectService = bTProjectService;
            _btRolesService = bTRolesService;
            _userManager = userManager;
            _btFileService = bTFileService;
            _imageService = imageService;
        }

        // GET: Projects
        public async Task<IActionResult> Index(int? pageNum)
        {
            //IPagedList<Project> projects;
            //// new service included
            //int pageSize = 4;
            //int page = pageNum ?? 1;

            //projects = await (await _btProjectService.GetAllProjectsASync()).ToPagedListAsync(page, pageSize);
            //return View(projects);
            List<Project> results;
            results = await _btProjectService.GetAllProjectsByCompanyIdAsync(_companyId);
            return View(results.ToList());

        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            // modify the code for the Service layer once it is working as it should here

            if (id == null)
            {
                return NotFound();
            }


            var project = await _btProjectService.GetProjectByIdAsync(id, _companyId);



            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult Create()
        {

            ViewData["ProjectPriority"] = new SelectList(_context.ProjectPriorities, "Id", "Name");
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,StartDate,EndDate,ProjectPriority,ImageFileData,ImageFileType,ImageFormFile,Archived")] Project project)
        {
            if (project != null)
            {

                ModelState.Remove(project.CompanyId.ToString());
                if (ModelState.IsValid)
                {
                    project.CompanyId = _companyId;
                    project.Created = DateTimeOffset.Now;

                    if (project.ImageFormFile != null)
                    {
                        // use image service
                        project.ImageFileData = await _imageService.ConvertFileToByteArrayAsynC(project.ImageFormFile);
                        project.ImageFileType = project.ImageFormFile.ContentType;
                    }

                    await _btProjectService.AddProjectAsync(project);
                   
                    _logger.LogInformation($"Project was successfully created: {DateTimeOffset.Now: MM dd, yyyy - HH:mm}");
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["ProjectPriority"] = new SelectList(_context.ProjectPriorities, "Id", "Name", project!.ProjectPriority);
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", _companyId);
            return View(project);
        }

        // GET: Projects/Edit/5
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Projects == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }

            ViewData["ProjectPriority"] = new SelectList(_context.ProjectPriorities, "Id", "Name", project.ProjectPriority);
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", _companyId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,CompanyId,Description,Created,StartDate,EndDate,ProjectPriority,ImageFileData,ImageFileType,ImageFomeFile,Archived")] Project project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (project.ImageFormFile != null)
                    {
                        // use image service
                        project.ImageFileData = await _imageService.ConvertFileToByteArrayAsynC(project.ImageFormFile);
                        project.ImageFileType = project.ImageFormFile.ContentType;
                    }
                    await _btProjectService.UpdateProjectAsync(project);
                    _logger.LogInformation($"Project was successfully updated: {DateTimeOffset.Now.ToUniversalTime()}");
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.Id))
                    {
                        _logger.LogError($"Project was not found: {DateTimeOffset.Now.ToUniversalTime()}");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectPriority"] = new SelectList(_context.ProjectPriorities, "Id", "Name", project.ProjectPriority);

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", _companyId);
            return View(project);
        }

        // GET: Projects/Delete/5
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Projects == null)
            {
                return NotFound();
            }
            Project? project = await _btProjectService.GetProjectByIdAsync(id, _companyId);
            
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await _btProjectService.GetProjectByIdAsync(id, _companyId) == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Projects'  is null.");
            }
            var project = await _btProjectService.GetProjectByIdAsync(id, _companyId);
            if (project != null)
            {
                await _btProjectService.ArchiveProjectAsync(project, _companyId);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // AssignPM Methods
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> AssignPM(int? id)
        {
            Project? project = await _btProjectService.GetProjectByIdAsync(id, _companyId);

            if (id == null) { return NotFound(); }

            //Get the list of project managers for the company
            IEnumerable<BTUser> projectManagers = await _btRolesService.GetUsersInRoleAsync(nameof(BTRoles.ProjectManager), _companyId);

            // Get the current PM if on is assigned
            BTUser? currentPM = await _btProjectService.GetProjectManagerAsync(id);

            // Instantiate and Initialize the ViewModel
            AssignPMViewModel vm = new()
            {
                ProjectId = project.Id,
                ProjectName = project.Name,
                PMList = new SelectList(projectManagers, "Id", "FullName", currentPM?.Id),
                PMId = currentPM?.Id,
            };

            return View(vm);
        }

        [HttpPost]

Views/Projects/AssignPM.cshtml
@model AssignPMViewModel

@{
    ViewData["Title"] = "Assign Project Manager";
}

<div class="d-flex justify-content-center mt-5 flex-column align-items-center">
    <h3 class="my-5">Assign Project Manager</h3>
    <div class="card">
        <div class="card-header">
            <div class="card-title">@Model.ProjectName</div>
        </div>
        <div class="card-body">
            <form asp-action="AssignPM" asp-controller="Projects" method="post" class="d-flex flex-column">
                <div asp-validation-summary="ModelOnly" class="text-danger" enctype="multipart/form-data"></div>
                <input type="hidden" asp-for="ProjectId" />
                <div class="form-group">
                    <label asp-for="PMId" class="control-label"></label>
                    <select asp-items="Model.PMList" asp-for="PMId">
                        <option value="">Unassigned</option>
                    </select>
                    <span asp-validation-for="PMId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary my-3">Save</button>
                    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Projects/AssignProjectMembers.cshtml
@model AssignMembersVM

@{
    ViewData["Title"] = "Assign Project Members";
}

<div class="d-flex justify-content-center mt-5 flex-column align-items-center">
    <h3 class="my-5">Assign Project Manager</h3>
    <div class="card">
        <div class="card-header">
            <div class="card-title">@Model.ProjectName</div>
        </div>
        <div class="card-body">
            <form asp-action="AssignProjectMembers" asp-controller="Projects" method="post" class="d-flex flex-column">
                <div asp-validation-summary="ModelOnly" class="text-danger" enctype="multipart/form-data"></div>
                <input type="hidden" asp-for="ProjectId" />
                <div class="form-group">
                    <label asp-for="PMId" class="control-label"></label>
                    <select name="Selected" asp-items="Model.MembersList" asp-items="ViewBag.MemberList" multiple size="6">
                        <option value="">Unassigned</option>
                    </select>
                    
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary my-3">Save</button>
                    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Projects/Create.cshtml
@model Guardian_BugTracker_23.Models.Project
@using Guardian_BugTracker_23.Services.Interfaces
@inject IBTFileService _fileService
@inject IImageService _imageService

@{
    ViewData["Title"] = "Create";
}
<div>
    <div class="content w-100">
    <div class="d-flex justify-content-between">
        <div class="row">
            <div class="col-md-12">
                <div class="card w-100">
                    <div class="card-header w-100">
                        <h1>Create</h1>
                        <h4>Create a new project</h4>
                    </div>
                    <div class="card-body w-100">
                        <div class="row">
                        <div class="col">
                            <form asp-action="Create" asp-controller="Projects" method="post" enctype="multipart/form-data">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>           
                                <input type="hidden" asp-for="CompanyId" />
                                <div class="form-group">
                                    <label asp-for="Name" class="control-label"></label>
                                    <input asp-for="Name" class="form-control" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>            
                                <div class="form-group">
                                    <label asp-for="Description" class="control-label"></label>
                                    <input asp-for="Description" class="form-control" />
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                                @* <div class="form-group">
                                    <label asp-for="Created" class="control-label"></label>
                                    <input asp-for="Created" class="form-control" />
                                    <span asp-validation-for="Created" class="text-danger"></span>
                                </div> *@
                                <div class="form-group">
                                    <label asp-for="StartDate" class="control-label"></label>
                                    <input asp-for="StartDate" class="form-control" />
                                    <span asp-validation-for="StartDate" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="EndDate" class="control-label"></label>
                                    <input asp-for="EndDate" class="form-control" />
                                    <span asp-validation-for="EndDate" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="ProjectPriority" class="control-label"></label>
                                    <select name="ProjectPriority" class="form-control" asp-items="ViewBag.ProjectPriority"></select>
                                    <span asp-validation-for="ProjectPriority" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="ImageFormFile" class="control-label">Project Image</label>
                                    <img class="img-fluid border rounded-3 mb-2 border border-1 border-secondary" style="max-height: 350px;" src="@_imageService.ConvertByteArrayToFile(Model?.ImageFileData!, Model?.ImageFileType!, DefaultImage.ProjectImage)" id="projectImage">
                                    <input asp-for="ImageFormFile" type="file" class="form-control mt-3 pt-2 border border-1 border-secondary" accept=".png,.jpg,.jpeg,.gif"
                                           onchange="document.getElementById('projectImage').src = window.URL.createObjectURL(this.files[0])" />
                                </div>
                                <div class="form-group form-check">
                                    <label class="form-check-label">
                                        <input class="form-check-input" asp-for="Archived" /> @Html.DisplayNameFor(model => model.Archived)
                                    </label>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                
                                </div>
                            </form>
                        </div>
                    </div>
                    </div>
                    <div class="card-footer w-100">
                        <div>
                            <a asp-action="Index">Back to List</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Projects/Delete.cshtml
@model Guardian_BugTracker_23.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPriority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPriority)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFileData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFileType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Archived)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Archived)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Projects/Edit.cshtml
@model Guardian_BugTracker_23.Models.Project

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CompanyId" />
            <input type="hidden" asp-for="Created" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="CompanyId" class="control-label"></label>
                <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.CompanyId"></select>
                <span asp-validation-for="CompanyId" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectPriority" class="control-label"></label>
                <select name="ProjectPriority" class="form-control" asp-items="ViewBag.ProjectPriority"></select>
                <span asp-validation-for="ProjectPriority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFileData" class="control-label"></label>
                <input asp-for="ImageFileData" class="form-control" />
                <span asp-validation-for="ImageFileData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFileType" class="control-label"></label>
                <input asp-for="ImageFileType" class="form-control" />
                <span asp-validation-for="ImageFileType" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Archived" /> @Html.DisplayNameFor(model => model.Archived)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Projects/RemoveAllTeamMembers.cshtml
@model AssignMembersVM

@{
    ViewData["Title"] = "Remove Project Members";
}

<div class="d-flex justify-content-center mt-5 flex-column align-items-center">
    <h3 class="my-5">Assign Project Manager</h3>
    <div class="card">
        <div class="card-header">
            <div class="card-title">@Model.ProjectName</div>
        </div>
        <div class="card-body">
            <form asp-action="RemoveAllTeamMembers" asp-controller="Projects" method="post" class="d-flex flex-column">
                <div asp-validation-summary="ModelOnly" class="text-danger" enctype="multipart/form-data"></div>
                <input type="hidden" asp-for="ProjectId" />
                <div>
                    <p class="display-5 text-danger">Are you sure you want to remove all team members?</p>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-danger my-3">Remove</button>
                    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Projects/Restore.cshtml
@model Guardian_BugTracker_23.Models.Project

@{
    ViewData["Title"] = "Restore";
}

<h1>Restore Archived Ticket</h1>

<h3>Are you sure you want to restore this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPriority)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProjectPriority)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileData)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageFileData)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageFileType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Archived)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Archived)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Company!.Name)
        </dd>
    </dl>

    <form asp-action="Restore">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Restore" class="btn btn-primary" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>